version: '3'
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports: 
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
  postgis_db:
    image: pgrouting/pgrouting
    container_name: pgrouting_container
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/postgresql/data