version: '3'
services:
  pgadmin4:
    image: dpage/pgadmin4
    ports: 
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
  postgis_db:
    image: postgis/postgis
    restart: always
    ports:
    - 5432:5430
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data